mv ./admin/ambari-admin.html.md.erb ./admin/ambari-admin.md
mv ./admin/ambari-rest-api.html.md.erb ./admin/ambari-rest-api.md
mv ./admin/BackingUpandRestoringHAWQDatabases.html.md.erb ./admin/BackingUpandRestoringHAWQDatabases.md
mv ./admin/ClusterExpansion.html.md.erb ./admin/ClusterExpansion.md
mv ./admin/ClusterShrink.html.md.erb ./admin/ClusterShrink.md
mv ./admin/FaultTolerance.html.md.erb ./admin/FaultTolerance.md
mv ./admin/HAWQFilespacesandHighAvailabilityEnabledHDFS.html.md.erb ./admin/HAWQFilespacesandHighAvailabilityEnabledHDFS.md
mv ./admin/HighAvailability.html.md.erb ./admin/HighAvailability.md
mv ./admin/logfiles.html.md.erb ./admin/logfiles.md
mv ./admin/maintain.html.md.erb ./admin/maintain.md
mv ./admin/MasterMirroring.html.md.erb ./admin/MasterMirroring.md
mv ./admin/monitor.html.md.erb ./admin/monitor.md
mv ./admin/RecommendedMonitoringTasks.html.md.erb ./admin/RecommendedMonitoringTasks.md
mv ./admin/RunningHAWQ.html.md.erb ./admin/RunningHAWQ.md
mv ./admin/setuphawqopenv.html.md.erb ./admin/setuphawqopenv.md
mv ./admin/startstop.html.md.erb ./admin/startstop.md
mv ./bestpractices/config_hawq_bestpractices.html.md.erb ./bestpractices/config_hawq_bestpractices.md
mv ./bestpractices/general_bestpractices.html.md.erb ./bestpractices/general_bestpractices.md
mv ./bestpractices/HAWQBestPracticesOverview.html.md.erb ./bestpractices/HAWQBestPracticesOverview.md
mv ./bestpractices/managing_data_bestpractices.html.md.erb ./bestpractices/managing_data_bestpractices.md
mv ./bestpractices/managing_resources_bestpractices.html.md.erb ./bestpractices/managing_resources_bestpractices.md
mv ./bestpractices/operating_hawq_bestpractices.html.md.erb ./bestpractices/operating_hawq_bestpractices.md
mv ./bestpractices/querying_data_bestpractices.html.md.erb ./bestpractices/querying_data_bestpractices.md
mv ./bestpractices/secure_bestpractices.html.md.erb ./bestpractices/secure_bestpractices.md
mv ./clientaccess/client_auth.html.md.erb ./clientaccess/client_auth.md
mv ./clientaccess/disable-kerberos.html.md.erb ./clientaccess/disable-kerberos.md
mv ./clientaccess/g-connecting-with-psql.html.md.erb ./clientaccess/g-connecting-with-psql.md
mv ./clientaccess/g-database-application-interfaces.html.md.erb ./clientaccess/g-database-application-interfaces.md
mv ./clientaccess/g-establishing-a-database-session.html.md.erb ./clientaccess/g-establishing-a-database-session.md
mv ./clientaccess/g-hawq-database-client-applications.html.md.erb ./clientaccess/g-hawq-database-client-applications.md
mv ./clientaccess/g-supported-client-applications.html.md.erb ./clientaccess/g-supported-client-applications.md
mv ./clientaccess/g-troubleshooting-connection-problems.html.md.erb ./clientaccess/g-troubleshooting-connection-problems.md
mv ./clientaccess/hawq-access-checks.html.md.erb ./clientaccess/hawq-access-checks.md
mv ./clientaccess/index.md.erb ./clientaccess/index.md.erb
mv ./clientaccess/kerberos.html.md.erb ./clientaccess/kerberos.md
mv ./clientaccess/ldap.html.md.erb ./clientaccess/ldap.md
mv ./clientaccess/roles_privs.html.md.erb ./clientaccess/roles_privs.md
mv ./datamgmt/about_statistics.html.md.erb ./datamgmt/about_statistics.md
mv ./datamgmt/BasicDataOperations.html.md.erb ./datamgmt/BasicDataOperations.md
mv ./datamgmt/ConcurrencyControl.html.md.erb ./datamgmt/ConcurrencyControl.md
mv ./datamgmt/dml.html.md.erb ./datamgmt/dml.md
mv ./datamgmt/HAWQInputFormatforMapReduce.html.md.erb ./datamgmt/HAWQInputFormatforMapReduce.md
mv ./datamgmt/load/client-loadtools.html.md.erb ./datamgmt/load/client-loadtools.md
mv ./datamgmt/load/creating-external-tables-examples.html.md.erb ./datamgmt/load/creating-external-tables-examples.md
mv ./datamgmt/load/g-about-gpfdist-setup-and-performance.html.md.erb ./datamgmt/load/g-about-gpfdist-setup-and-performance.md
mv ./datamgmt/load/g-character-encoding.html.md.erb ./datamgmt/load/g-character-encoding.md
mv ./datamgmt/load/g-command-based-web-external-tables.html.md.erb ./datamgmt/load/g-command-based-web-external-tables.md
mv ./datamgmt/load/g-configuration-file-format.html.md.erb ./datamgmt/load/g-configuration-file-format.md
mv ./datamgmt/load/g-controlling-segment-parallelism.html.md.erb ./datamgmt/load/g-controlling-segment-parallelism.md
mv ./datamgmt/load/g-create-an-error-table-and-declare-a-reject-limit.html.md.erb ./datamgmt/load/g-create-an-error-table-and-declare-a-reject-limit.md
mv ./datamgmt/load/g-creating-and-using-web-external-tables.html.md.erb ./datamgmt/load/g-creating-and-using-web-external-tables.md
mv ./datamgmt/load/g-define-an-external-table-with-single-row-error-isolation.html.md.erb ./datamgmt/load/g-define-an-external-table-with-single-row-error-isolation.md
mv ./datamgmt/load/g-defining-a-command-based-writable-external-web-table.html.md.erb ./datamgmt/load/g-defining-a-command-based-writable-external-web-table.md
mv ./datamgmt/load/g-defining-a-file-based-writable-external-table.html.md.erb ./datamgmt/load/g-defining-a-file-based-writable-external-table.md
mv ./datamgmt/load/g-determine-the-transformation-schema.html.md.erb ./datamgmt/load/g-determine-the-transformation-schema.md
mv ./datamgmt/load/g-disabling-execute-for-web-or-writable-external-tables.html.md.erb ./datamgmt/load/g-disabling-execute-for-web-or-writable-external-tables.md
mv ./datamgmt/load/g-escaping-in-csv-formatted-files.html.md.erb ./datamgmt/load/g-escaping-in-csv-formatted-files.md
mv ./datamgmt/load/g-escaping-in-text-formatted-files.html.md.erb ./datamgmt/load/g-escaping-in-text-formatted-files.md
mv ./datamgmt/load/g-escaping.html.md.erb ./datamgmt/load/g-escaping.md
mv ./datamgmt/load/g-example-1-dblp-database-publications-in-demo-directory.html.md.erb ./datamgmt/load/g-example-1-dblp-database-publications-in-demo-directory.md
mv ./datamgmt/load/g-example-hawq-file-server-gpfdist.html.md.erb ./datamgmt/load/g-example-hawq-file-server-gpfdist.md
mv ./datamgmt/load/g-example-irs-mef-xml-files-in-demo-directory.html.md.erb ./datamgmt/load/g-example-irs-mef-xml-files-in-demo-directory.md
mv ./datamgmt/load/g-example-witsml-files-in-demo-directory.html.md.erb ./datamgmt/load/g-example-witsml-files-in-demo-directory.md
mv ./datamgmt/load/g-examples-read-fixed-width-data.html.md.erb ./datamgmt/load/g-examples-read-fixed-width-data.md
mv ./datamgmt/load/g-external-tables.html.md.erb ./datamgmt/load/g-external-tables.md
mv ./datamgmt/load/g-formatting-columns.html.md.erb ./datamgmt/load/g-formatting-columns.md
mv ./datamgmt/load/g-formatting-data-files.html.md.erb ./datamgmt/load/g-formatting-data-files.md
mv ./datamgmt/load/g-formatting-rows.html.md.erb ./datamgmt/load/g-formatting-rows.md
mv ./datamgmt/load/g-gpfdist-protocol.html.md.erb ./datamgmt/load/g-gpfdist-protocol.md
mv ./datamgmt/load/g-gpfdists-protocol.html.md.erb ./datamgmt/load/g-gpfdists-protocol.md
mv ./datamgmt/load/g-handling-errors-ext-table-data.html.md.erb ./datamgmt/load/g-handling-errors-ext-table-data.md
mv ./datamgmt/load/g-handling-load-errors.html.md.erb ./datamgmt/load/g-handling-load-errors.md
mv ./datamgmt/load/g-identifying-invalid-csv-files-in-error-table-data.html.md.erb ./datamgmt/load/g-identifying-invalid-csv-files-in-error-table-data.md
mv ./datamgmt/load/g-importing-and-exporting-fixed-width-data.html.md.erb ./datamgmt/load/g-importing-and-exporting-fixed-width-data.md
mv ./datamgmt/load/g-installing-gpfdist.html.md.erb ./datamgmt/load/g-installing-gpfdist.md
mv ./datamgmt/load/g-load-the-data.html.md.erb ./datamgmt/load/g-load-the-data.md
mv ./datamgmt/load/g-loading-and-unloading-data.html.md.erb ./datamgmt/load/g-loading-and-unloading-data.md
mv ./datamgmt/load/g-loading-and-writing-non-hdfs-custom-data.html.md.erb ./datamgmt/load/g-loading-and-writing-non-hdfs-custom-data.md
mv ./datamgmt/load/g-loading-data-using-an-external-table.html.md.erb ./datamgmt/load/g-loading-data-using-an-external-table.md
mv ./datamgmt/load/g-loading-data-with-copy.html.md.erb ./datamgmt/load/g-loading-data-with-copy.md
mv ./datamgmt/load/g-loading-data-with-hawqload.html.md.erb ./datamgmt/load/g-loading-data-with-hawqload.md
mv ./datamgmt/load/g-moving-data-between-tables.html.md.erb ./datamgmt/load/g-moving-data-between-tables.md
mv ./datamgmt/load/g-optimizing-data-load-and-query-performance.html.md.erb ./datamgmt/load/g-optimizing-data-load-and-query-performance.md
mv ./datamgmt/load/g-register_files.html.md.erb ./datamgmt/load/g-register_files.md
mv ./datamgmt/load/g-representing-null-values.html.md.erb ./datamgmt/load/g-representing-null-values.md
mv ./datamgmt/load/g-running-copy-in-single-row-error-isolation-mode.html.md.erb ./datamgmt/load/g-running-copy-in-single-row-error-isolation-mode.md
mv ./datamgmt/load/g-starting-and-stopping-gpfdist.html.md.erb ./datamgmt/load/g-starting-and-stopping-gpfdist.md
mv ./datamgmt/load/g-transfer-and-store-the-data.html.md.erb ./datamgmt/load/g-transfer-and-store-the-data.md
mv ./datamgmt/load/g-transforming-with-gpload.html.md.erb ./datamgmt/load/g-transforming-with-gpload.md
mv ./datamgmt/load/g-transforming-with-insert-into-select-from.html.md.erb ./datamgmt/load/g-transforming-with-insert-into-select-from.md
mv ./datamgmt/load/g-transforming-xml-data.html.md.erb ./datamgmt/load/g-transforming-xml-data.md
mv ./datamgmt/load/g-troubleshooting-gpfdist.html.md.erb ./datamgmt/load/g-troubleshooting-gpfdist.md
mv ./datamgmt/load/g-unloading-data-from-hawq-database.html.md.erb ./datamgmt/load/g-unloading-data-from-hawq-database.md
mv ./datamgmt/load/g-unloading-data-using-a-writable-external-table.html.md.erb ./datamgmt/load/g-unloading-data-using-a-writable-external-table.md
mv ./datamgmt/load/g-unloading-data-using-copy.html.md.erb ./datamgmt/load/g-unloading-data-using-copy.md
mv ./datamgmt/load/g-url-based-web-external-tables.html.md.erb ./datamgmt/load/g-url-based-web-external-tables.md
mv ./datamgmt/load/g-using-a-custom-format.html.md.erb ./datamgmt/load/g-using-a-custom-format.md
mv ./datamgmt/load/g-using-the-hawq-file-server--gpfdist-.html.md.erb ./datamgmt/load/g-using-the-hawq-file-server--gpfdist-.md
mv ./datamgmt/load/g-working-with-file-based-ext-tables.html.md.erb ./datamgmt/load/g-working-with-file-based-ext-tables.md
mv ./datamgmt/load/g-write-a-transform.html.md.erb ./datamgmt/load/g-write-a-transform.md
mv ./datamgmt/load/g-write-the-gpfdist-configuration.html.md.erb ./datamgmt/load/g-write-the-gpfdist-configuration.md
mv ./datamgmt/load/g-xml-transformation-examples.html.md.erb ./datamgmt/load/g-xml-transformation-examples.md
mv ./datamgmt/Transactions.html.md.erb ./datamgmt/Transactions.md
mv ./ddl/ddl-database.html.md.erb ./ddl/ddl-database.md
mv ./ddl/ddl-partition.html.md.erb ./ddl/ddl-partition.md
mv ./ddl/ddl-schema.html.md.erb ./ddl/ddl-schema.md
mv ./ddl/ddl-storage.html.md.erb ./ddl/ddl-storage.md
mv ./ddl/ddl-table.html.md.erb ./ddl/ddl-table.md
mv ./ddl/ddl-tablespace.html.md.erb ./ddl/ddl-tablespace.md
mv ./ddl/ddl-view.html.md.erb ./ddl/ddl-view.md
mv ./ddl/ddl.html.md.erb ./ddl/ddl.md
mv ./ddl/locate-table-hdfs.html.md.erb ./ddl/locate-table-hdfs.md
mv ./index.html.erb ./index.html.erb
mv ./install/aws-config.html.md.erb ./install/aws-config.md
mv ./install/select-hosts.html.md.erb ./install/select-hosts.md
mv ./overview/ElasticSegments.html.md.erb ./overview/ElasticSegments.md
mv ./overview/HAWQArchitecture.html.md.erb ./overview/HAWQArchitecture.md
mv ./overview/HAWQOverview.html.md.erb ./overview/HAWQOverview.md
mv ./overview/HDFSCatalogCache.html.md.erb ./overview/HDFSCatalogCache.md
mv ./overview/ManagementTools.html.md.erb ./overview/ManagementTools.md
mv ./overview/RedundancyFailover.html.md.erb ./overview/RedundancyFailover.md
mv ./overview/ResourceManagement.html.md.erb ./overview/ResourceManagement.md
mv ./overview/system-overview.html.md.erb ./overview/system-overview.md
mv ./overview/TableDistributionStorage.html.md.erb ./overview/TableDistributionStorage.md
mv ./plext/builtin_langs.html.md.erb ./plext/builtin_langs.md
mv ./plext/UsingProceduralLanguages.html.md.erb ./plext/UsingProceduralLanguages.md
mv ./plext/using_pgcrypto.html.md.erb ./plext/using_pgcrypto.md
mv ./plext/using_pljava.html.md.erb ./plext/using_pljava.md
mv ./plext/using_plperl.html.md.erb ./plext/using_plperl.md
mv ./plext/using_plpgsql.html.md.erb ./plext/using_plpgsql.md
mv ./plext/using_plpython.html.md.erb ./plext/using_plpython.md
mv ./plext/using_plr.html.md.erb ./plext/using_plr.md
mv ./pxf/ConfigurePXF.html.md.erb ./pxf/ConfigurePXF.md
mv ./pxf/HawqExtensionFrameworkPXF.html.md.erb ./pxf/HawqExtensionFrameworkPXF.md
mv ./pxf/HBasePXF.html.md.erb ./pxf/HBasePXF.md
mv ./pxf/HDFSFileDataPXF.html.md.erb ./pxf/HDFSFileDataPXF.md
mv ./pxf/HDFSWritablePXF.html.md.erb ./pxf/HDFSWritablePXF.md
mv ./pxf/HivePXF.html.md.erb ./pxf/HivePXF.md
mv ./pxf/InstallPXFPlugins.html.md.erb ./pxf/InstallPXFPlugins.md
mv ./pxf/JsonPXF.html.md.erb ./pxf/JsonPXF.md
mv ./pxf/PXFExternalTableandAPIReference.html.md.erb ./pxf/PXFExternalTableandAPIReference.md
mv ./pxf/ReadWritePXF.html.md.erb ./pxf/ReadWritePXF.md
mv ./pxf/TroubleshootingPXF.html.md.erb ./pxf/TroubleshootingPXF.md
mv ./query/defining-queries.html.md.erb ./query/defining-queries.md
mv ./query/functions-operators.html.md.erb ./query/functions-operators.md
mv ./query/gporca/query-gporca-changed.html.md.erb ./query/gporca/query-gporca-changed.md
mv ./query/gporca/query-gporca-enable.html.md.erb ./query/gporca/query-gporca-enable.md
mv ./query/gporca/query-gporca-fallback.html.md.erb ./query/gporca/query-gporca-fallback.md
mv ./query/gporca/query-gporca-features.html.md.erb ./query/gporca/query-gporca-features.md
mv ./query/gporca/query-gporca-limitations.html.md.erb ./query/gporca/query-gporca-limitations.md
mv ./query/gporca/query-gporca-notes.html.md.erb ./query/gporca/query-gporca-notes.md
mv ./query/gporca/query-gporca-optimizer.html.md.erb ./query/gporca/query-gporca-optimizer.md
mv ./query/gporca/query-gporca-overview.html.md.erb ./query/gporca/query-gporca-overview.md
mv ./query/HAWQQueryProcessing.html.md.erb ./query/HAWQQueryProcessing.md
mv ./query/query-performance.html.md.erb ./query/query-performance.md
mv ./query/query-profiling.html.md.erb ./query/query-profiling.md
mv ./query/query.html.md.erb ./query/query.md
mv ./ranger/madlib-ranger.html.md.erb ./ranger/madlib-ranger.md
mv ./ranger/ranger-auditing.html.md.erb ./ranger/ranger-auditing.md
mv ./ranger/ranger-integration-config.html.md.erb ./ranger/ranger-integration-config.md
mv ./ranger/ranger-overview.html.md.erb ./ranger/ranger-overview.md
mv ./ranger/ranger-policy-creation.html.md.erb ./ranger/ranger-policy-creation.md
mv ./ranger/ranger-resource-perms.html.md.erb ./ranger/ranger-resource-perms.md
mv ./ranger/ranger-sqlcmd-summary.html.md.erb ./ranger/ranger-sqlcmd-summary.md
mv ./reference/catalog/catalog_ref-html.html.md.erb ./reference/catalog/catalog_ref-html.md
mv ./reference/catalog/catalog_ref-tables.html.md.erb ./reference/catalog/catalog_ref-tables.md
mv ./reference/catalog/catalog_ref-views.html.md.erb ./reference/catalog/catalog_ref-views.md
mv ./reference/catalog/catalog_ref.html.md.erb ./reference/catalog/catalog_ref.md
mv ./reference/catalog/gp_configuration_history.html.md.erb ./reference/catalog/gp_configuration_history.md
mv ./reference/catalog/gp_distribution_policy.html.md.erb ./reference/catalog/gp_distribution_policy.md
mv ./reference/catalog/gp_global_sequence.html.md.erb ./reference/catalog/gp_global_sequence.md
mv ./reference/catalog/gp_master_mirroring.html.md.erb ./reference/catalog/gp_master_mirroring.md
mv ./reference/catalog/gp_persistent_database_node.html.md.erb ./reference/catalog/gp_persistent_database_node.md
mv ./reference/catalog/gp_persistent_filespace_node.html.md.erb ./reference/catalog/gp_persistent_filespace_node.md
mv ./reference/catalog/gp_persistent_relation_node.html.md.erb ./reference/catalog/gp_persistent_relation_node.md
mv ./reference/catalog/gp_persistent_relfile_node.html.md.erb ./reference/catalog/gp_persistent_relfile_node.md
mv ./reference/catalog/gp_persistent_tablespace_node.html.md.erb ./reference/catalog/gp_persistent_tablespace_node.md
mv ./reference/catalog/gp_relfile_node.html.md.erb ./reference/catalog/gp_relfile_node.md
mv ./reference/catalog/gp_segment_configuration.html.md.erb ./reference/catalog/gp_segment_configuration.md
mv ./reference/catalog/gp_version_at_initdb.html.md.erb ./reference/catalog/gp_version_at_initdb.md
mv ./reference/catalog/pg_aggregate.html.md.erb ./reference/catalog/pg_aggregate.md
mv ./reference/catalog/pg_am.html.md.erb ./reference/catalog/pg_am.md
mv ./reference/catalog/pg_amop.html.md.erb ./reference/catalog/pg_amop.md
mv ./reference/catalog/pg_amproc.html.md.erb ./reference/catalog/pg_amproc.md
mv ./reference/catalog/pg_appendonly.html.md.erb ./reference/catalog/pg_appendonly.md
mv ./reference/catalog/pg_attrdef.html.md.erb ./reference/catalog/pg_attrdef.md
mv ./reference/catalog/pg_attribute.html.md.erb ./reference/catalog/pg_attribute.md
mv ./reference/catalog/pg_attribute_encoding.html.md.erb ./reference/catalog/pg_attribute_encoding.md
mv ./reference/catalog/pg_authid.html.md.erb ./reference/catalog/pg_authid.md
mv ./reference/catalog/pg_auth_members.html.md.erb ./reference/catalog/pg_auth_members.md
mv ./reference/catalog/pg_cast.html.md.erb ./reference/catalog/pg_cast.md
mv ./reference/catalog/pg_class.html.md.erb ./reference/catalog/pg_class.md
mv ./reference/catalog/pg_compression.html.md.erb ./reference/catalog/pg_compression.md
mv ./reference/catalog/pg_constraint.html.md.erb ./reference/catalog/pg_constraint.md
mv ./reference/catalog/pg_conversion.html.md.erb ./reference/catalog/pg_conversion.md
mv ./reference/catalog/pg_database.html.md.erb ./reference/catalog/pg_database.md
mv ./reference/catalog/pg_depend.html.md.erb ./reference/catalog/pg_depend.md
mv ./reference/catalog/pg_description.html.md.erb ./reference/catalog/pg_description.md
mv ./reference/catalog/pg_exttable.html.md.erb ./reference/catalog/pg_exttable.md
mv ./reference/catalog/pg_filespace.html.md.erb ./reference/catalog/pg_filespace.md
mv ./reference/catalog/pg_filespace_entry.html.md.erb ./reference/catalog/pg_filespace_entry.md
mv ./reference/catalog/pg_index.html.md.erb ./reference/catalog/pg_index.md
mv ./reference/catalog/pg_inherits.html.md.erb ./reference/catalog/pg_inherits.md
mv ./reference/catalog/pg_language.html.md.erb ./reference/catalog/pg_language.md
mv ./reference/catalog/pg_largeobject.html.md.erb ./reference/catalog/pg_largeobject.md
mv ./reference/catalog/pg_listener.html.md.erb ./reference/catalog/pg_listener.md
mv ./reference/catalog/pg_locks.html.md.erb ./reference/catalog/pg_locks.md
mv ./reference/catalog/pg_namespace.html.md.erb ./reference/catalog/pg_namespace.md
mv ./reference/catalog/pg_opclass.html.md.erb ./reference/catalog/pg_opclass.md
mv ./reference/catalog/pg_operator.html.md.erb ./reference/catalog/pg_operator.md
mv ./reference/catalog/pg_partition.html.md.erb ./reference/catalog/pg_partition.md
mv ./reference/catalog/pg_partitions.html.md.erb ./reference/catalog/pg_partitions.md
mv ./reference/catalog/pg_partition_columns.html.md.erb ./reference/catalog/pg_partition_columns.md
mv ./reference/catalog/pg_partition_encoding.html.md.erb ./reference/catalog/pg_partition_encoding.md
mv ./reference/catalog/pg_partition_rule.html.md.erb ./reference/catalog/pg_partition_rule.md
mv ./reference/catalog/pg_partition_templates.html.md.erb ./reference/catalog/pg_partition_templates.md
mv ./reference/catalog/pg_pltemplate.html.md.erb ./reference/catalog/pg_pltemplate.md
mv ./reference/catalog/pg_proc.html.md.erb ./reference/catalog/pg_proc.md
mv ./reference/catalog/pg_resqueue.html.md.erb ./reference/catalog/pg_resqueue.md
mv ./reference/catalog/pg_resqueue_status.html.md.erb ./reference/catalog/pg_resqueue_status.md
mv ./reference/catalog/pg_rewrite.html.md.erb ./reference/catalog/pg_rewrite.md
mv ./reference/catalog/pg_roles.html.md.erb ./reference/catalog/pg_roles.md
mv ./reference/catalog/pg_shdepend.html.md.erb ./reference/catalog/pg_shdepend.md
mv ./reference/catalog/pg_shdescription.html.md.erb ./reference/catalog/pg_shdescription.md
mv ./reference/catalog/pg_statistic.html.md.erb ./reference/catalog/pg_statistic.md
mv ./reference/catalog/pg_stats.html.md.erb ./reference/catalog/pg_stats.md
mv ./reference/catalog/pg_stat_activity.html.md.erb ./reference/catalog/pg_stat_activity.md
mv ./reference/catalog/pg_stat_last_operation.html.md.erb ./reference/catalog/pg_stat_last_operation.md
mv ./reference/catalog/pg_stat_last_shoperation.html.md.erb ./reference/catalog/pg_stat_last_shoperation.md
mv ./reference/catalog/pg_stat_operations.html.md.erb ./reference/catalog/pg_stat_operations.md
mv ./reference/catalog/pg_stat_partition_operations.html.md.erb ./reference/catalog/pg_stat_partition_operations.md
mv ./reference/catalog/pg_tablespace.html.md.erb ./reference/catalog/pg_tablespace.md
mv ./reference/catalog/pg_trigger.html.md.erb ./reference/catalog/pg_trigger.md
mv ./reference/catalog/pg_type.html.md.erb ./reference/catalog/pg_type.md
mv ./reference/catalog/pg_type_encoding.html.md.erb ./reference/catalog/pg_type_encoding.md
mv ./reference/catalog/pg_window.html.md.erb ./reference/catalog/pg_window.md
mv ./reference/CharacterSetSupportReference.html.md.erb ./reference/CharacterSetSupportReference.md
mv ./reference/cli/admin_utilities/analyzedb.html.md.erb ./reference/cli/admin_utilities/analyzedb.md
mv ./reference/cli/admin_utilities/gpfdist.html.md.erb ./reference/cli/admin_utilities/gpfdist.md
mv ./reference/cli/admin_utilities/gplogfilter.html.md.erb ./reference/cli/admin_utilities/gplogfilter.md
mv ./reference/cli/admin_utilities/hawqactivate.html.md.erb ./reference/cli/admin_utilities/hawqactivate.md
mv ./reference/cli/admin_utilities/hawqcheck.html.md.erb ./reference/cli/admin_utilities/hawqcheck.md
mv ./reference/cli/admin_utilities/hawqcheckperf.html.md.erb ./reference/cli/admin_utilities/hawqcheckperf.md
mv ./reference/cli/admin_utilities/hawqconfig.html.md.erb ./reference/cli/admin_utilities/hawqconfig.md
mv ./reference/cli/admin_utilities/hawqextract.html.md.erb ./reference/cli/admin_utilities/hawqextract.md
mv ./reference/cli/admin_utilities/hawqfilespace.html.md.erb ./reference/cli/admin_utilities/hawqfilespace.md
mv ./reference/cli/admin_utilities/hawqinit.html.md.erb ./reference/cli/admin_utilities/hawqinit.md
mv ./reference/cli/admin_utilities/hawqload.html.md.erb ./reference/cli/admin_utilities/hawqload.md
mv ./reference/cli/admin_utilities/hawqregister.html.md.erb ./reference/cli/admin_utilities/hawqregister.md
mv ./reference/cli/admin_utilities/hawqrestart.html.md.erb ./reference/cli/admin_utilities/hawqrestart.md
mv ./reference/cli/admin_utilities/hawqscp.html.md.erb ./reference/cli/admin_utilities/hawqscp.md
mv ./reference/cli/admin_utilities/hawqssh-exkeys.html.md.erb ./reference/cli/admin_utilities/hawqssh-exkeys.md
mv ./reference/cli/admin_utilities/hawqssh.html.md.erb ./reference/cli/admin_utilities/hawqssh.md
mv ./reference/cli/admin_utilities/hawqstart.html.md.erb ./reference/cli/admin_utilities/hawqstart.md
mv ./reference/cli/admin_utilities/hawqstate.html.md.erb ./reference/cli/admin_utilities/hawqstate.md
mv ./reference/cli/admin_utilities/hawqstop.html.md.erb ./reference/cli/admin_utilities/hawqstop.md
mv ./reference/cli/client_utilities/createdb.html.md.erb ./reference/cli/client_utilities/createdb.md
mv ./reference/cli/client_utilities/createuser.html.md.erb ./reference/cli/client_utilities/createuser.md
mv ./reference/cli/client_utilities/dropdb.html.md.erb ./reference/cli/client_utilities/dropdb.md
mv ./reference/cli/client_utilities/dropuser.html.md.erb ./reference/cli/client_utilities/dropuser.md
mv ./reference/cli/client_utilities/pg_dump.html.md.erb ./reference/cli/client_utilities/pg_dump.md
mv ./reference/cli/client_utilities/pg_dumpall.html.md.erb ./reference/cli/client_utilities/pg_dumpall.md
mv ./reference/cli/client_utilities/pg_restore.html.md.erb ./reference/cli/client_utilities/pg_restore.md
mv ./reference/cli/client_utilities/psql.html.md.erb ./reference/cli/client_utilities/psql.md
mv ./reference/cli/client_utilities/vacuumdb.html.md.erb ./reference/cli/client_utilities/vacuumdb.md
mv ./reference/cli/management_tools.html.md.erb ./reference/cli/management_tools.md
mv ./reference/guc/guc_category-list.html.md.erb ./reference/guc/guc_category-list.md
mv ./reference/guc/guc_config.html.md.erb ./reference/guc/guc_config.md
mv ./reference/guc/parameter_definitions.html.md.erb ./reference/guc/parameter_definitions.md
mv ./reference/hawq-reference.html.md.erb ./reference/hawq-reference.md
mv ./reference/HAWQDataTypes.html.md.erb ./reference/HAWQDataTypes.md
mv ./reference/HAWQEnvironmentVariables.html.md.erb ./reference/HAWQEnvironmentVariables.md
mv ./reference/HAWQSampleSiteConfig.html.md.erb ./reference/HAWQSampleSiteConfig.md
mv ./reference/HAWQSiteConfig.html.md.erb ./reference/HAWQSiteConfig.md
mv ./reference/HDFSConfigurationParameterReference.html.md.erb ./reference/HDFSConfigurationParameterReference.md
mv ./reference/sql/ABORT.html.md.erb ./reference/sql/ABORT.md
mv ./reference/sql/ALTER-AGGREGATE.html.md.erb ./reference/sql/ALTER-AGGREGATE.md
mv ./reference/sql/ALTER-CONVERSION.html.md.erb ./reference/sql/ALTER-CONVERSION.md
mv ./reference/sql/ALTER-DATABASE.html.md.erb ./reference/sql/ALTER-DATABASE.md
mv ./reference/sql/ALTER-FUNCTION.html.md.erb ./reference/sql/ALTER-FUNCTION.md
mv ./reference/sql/ALTER-OPERATOR-CLASS.html.md.erb ./reference/sql/ALTER-OPERATOR-CLASS.md
mv ./reference/sql/ALTER-OPERATOR.html.md.erb ./reference/sql/ALTER-OPERATOR.md
mv ./reference/sql/ALTER-RESOURCE-QUEUE.html.md.erb ./reference/sql/ALTER-RESOURCE-QUEUE.md
mv ./reference/sql/ALTER-ROLE.html.md.erb ./reference/sql/ALTER-ROLE.md
mv ./reference/sql/ALTER-SEQUENCE.html.md.erb ./reference/sql/ALTER-SEQUENCE.md
mv ./reference/sql/ALTER-TABLE.html.md.erb ./reference/sql/ALTER-TABLE.md
mv ./reference/sql/ALTER-TABLESPACE.html.md.erb ./reference/sql/ALTER-TABLESPACE.md
mv ./reference/sql/ALTER-TYPE.html.md.erb ./reference/sql/ALTER-TYPE.md
mv ./reference/sql/ALTER-USER.html.md.erb ./reference/sql/ALTER-USER.md
mv ./reference/sql/ANALYZE.html.md.erb ./reference/sql/ANALYZE.md
mv ./reference/sql/BEGIN.html.md.erb ./reference/sql/BEGIN.md
mv ./reference/sql/CHECKPOINT.html.md.erb ./reference/sql/CHECKPOINT.md
mv ./reference/sql/CLOSE.html.md.erb ./reference/sql/CLOSE.md
mv ./reference/sql/COMMIT.html.md.erb ./reference/sql/COMMIT.md
mv ./reference/sql/COPY.html.md.erb ./reference/sql/COPY.md
mv ./reference/sql/CREATE-AGGREGATE.html.md.erb ./reference/sql/CREATE-AGGREGATE.md
mv ./reference/sql/CREATE-CAST.html.md.erb ./reference/sql/CREATE-CAST.md
mv ./reference/sql/CREATE-CONVERSION.html.md.erb ./reference/sql/CREATE-CONVERSION.md
mv ./reference/sql/CREATE-DATABASE.html.md.erb ./reference/sql/CREATE-DATABASE.md
mv ./reference/sql/CREATE-EXTERNAL-TABLE.html.md.erb ./reference/sql/CREATE-EXTERNAL-TABLE.md
mv ./reference/sql/CREATE-FUNCTION.html.md.erb ./reference/sql/CREATE-FUNCTION.md
mv ./reference/sql/CREATE-GROUP.html.md.erb ./reference/sql/CREATE-GROUP.md
mv ./reference/sql/CREATE-LANGUAGE.html.md.erb ./reference/sql/CREATE-LANGUAGE.md
mv ./reference/sql/CREATE-OPERATOR-CLASS.html.md.erb ./reference/sql/CREATE-OPERATOR-CLASS.md
mv ./reference/sql/CREATE-OPERATOR.html.md.erb ./reference/sql/CREATE-OPERATOR.md
mv ./reference/sql/CREATE-RESOURCE-QUEUE.html.md.erb ./reference/sql/CREATE-RESOURCE-QUEUE.md
mv ./reference/sql/CREATE-ROLE.html.md.erb ./reference/sql/CREATE-ROLE.md
mv ./reference/sql/CREATE-SCHEMA.html.md.erb ./reference/sql/CREATE-SCHEMA.md
mv ./reference/sql/CREATE-SEQUENCE.html.md.erb ./reference/sql/CREATE-SEQUENCE.md
mv ./reference/sql/CREATE-TABLE-AS.html.md.erb ./reference/sql/CREATE-TABLE-AS.md
mv ./reference/sql/CREATE-TABLE.html.md.erb ./reference/sql/CREATE-TABLE.md
mv ./reference/sql/CREATE-TABLESPACE.html.md.erb ./reference/sql/CREATE-TABLESPACE.md
mv ./reference/sql/CREATE-TYPE.html.md.erb ./reference/sql/CREATE-TYPE.md
mv ./reference/sql/CREATE-USER.html.md.erb ./reference/sql/CREATE-USER.md
mv ./reference/sql/CREATE-VIEW.html.md.erb ./reference/sql/CREATE-VIEW.md
mv ./reference/sql/DEALLOCATE.html.md.erb ./reference/sql/DEALLOCATE.md
mv ./reference/sql/DECLARE.html.md.erb ./reference/sql/DECLARE.md
mv ./reference/sql/DROP-AGGREGATE.html.md.erb ./reference/sql/DROP-AGGREGATE.md
mv ./reference/sql/DROP-CAST.html.md.erb ./reference/sql/DROP-CAST.md
mv ./reference/sql/DROP-CONVERSION.html.md.erb ./reference/sql/DROP-CONVERSION.md
mv ./reference/sql/DROP-DATABASE.html.md.erb ./reference/sql/DROP-DATABASE.md
mv ./reference/sql/DROP-EXTERNAL-TABLE.html.md.erb ./reference/sql/DROP-EXTERNAL-TABLE.md
mv ./reference/sql/DROP-FILESPACE.html.md.erb ./reference/sql/DROP-FILESPACE.md
mv ./reference/sql/DROP-FUNCTION.html.md.erb ./reference/sql/DROP-FUNCTION.md
mv ./reference/sql/DROP-GROUP.html.md.erb ./reference/sql/DROP-GROUP.md
mv ./reference/sql/DROP-LANGUAGE.html.md.erb ./reference/sql/DROP-LANGUAGE.md
mv ./reference/sql/DROP-OPERATOR-CLASS.html.md.erb ./reference/sql/DROP-OPERATOR-CLASS.md
mv ./reference/sql/DROP-OPERATOR.html.md.erb ./reference/sql/DROP-OPERATOR.md
mv ./reference/sql/DROP-OWNED.html.md.erb ./reference/sql/DROP-OWNED.md
mv ./reference/sql/DROP-RESOURCE-QUEUE.html.md.erb ./reference/sql/DROP-RESOURCE-QUEUE.md
mv ./reference/sql/DROP-ROLE.html.md.erb ./reference/sql/DROP-ROLE.md
mv ./reference/sql/DROP-SCHEMA.html.md.erb ./reference/sql/DROP-SCHEMA.md
mv ./reference/sql/DROP-SEQUENCE.html.md.erb ./reference/sql/DROP-SEQUENCE.md
mv ./reference/sql/DROP-TABLE.html.md.erb ./reference/sql/DROP-TABLE.md
mv ./reference/sql/DROP-TABLESPACE.html.md.erb ./reference/sql/DROP-TABLESPACE.md
mv ./reference/sql/DROP-TYPE.html.md.erb ./reference/sql/DROP-TYPE.md
mv ./reference/sql/DROP-USER.html.md.erb ./reference/sql/DROP-USER.md
mv ./reference/sql/DROP-VIEW.html.md.erb ./reference/sql/DROP-VIEW.md
mv ./reference/sql/END.html.md.erb ./reference/sql/END.md
mv ./reference/sql/EXECUTE.html.md.erb ./reference/sql/EXECUTE.md
mv ./reference/sql/EXPLAIN.html.md.erb ./reference/sql/EXPLAIN.md
mv ./reference/sql/FETCH.html.md.erb ./reference/sql/FETCH.md
mv ./reference/sql/GRANT.html.md.erb ./reference/sql/GRANT.md
mv ./reference/sql/INSERT.html.md.erb ./reference/sql/INSERT.md
mv ./reference/sql/PREPARE.html.md.erb ./reference/sql/PREPARE.md
mv ./reference/sql/REASSIGN-OWNED.html.md.erb ./reference/sql/REASSIGN-OWNED.md
mv ./reference/sql/RELEASE-SAVEPOINT.html.md.erb ./reference/sql/RELEASE-SAVEPOINT.md
mv ./reference/sql/RESET.html.md.erb ./reference/sql/RESET.md
mv ./reference/sql/REVOKE.html.md.erb ./reference/sql/REVOKE.md
mv ./reference/sql/ROLLBACK-TO-SAVEPOINT.html.md.erb ./reference/sql/ROLLBACK-TO-SAVEPOINT.md
mv ./reference/sql/ROLLBACK.html.md.erb ./reference/sql/ROLLBACK.md
mv ./reference/sql/SAVEPOINT.html.md.erb ./reference/sql/SAVEPOINT.md
mv ./reference/sql/SELECT-INTO.html.md.erb ./reference/sql/SELECT-INTO.md
mv ./reference/sql/SELECT.html.md.erb ./reference/sql/SELECT.md
mv ./reference/sql/SET-ROLE.html.md.erb ./reference/sql/SET-ROLE.md
mv ./reference/sql/SET-SESSION-AUTHORIZATION.html.md.erb ./reference/sql/SET-SESSION-AUTHORIZATION.md
mv ./reference/sql/SET.html.md.erb ./reference/sql/SET.md
mv ./reference/sql/SHOW.html.md.erb ./reference/sql/SHOW.md
mv ./reference/sql/TRUNCATE.html.md.erb ./reference/sql/TRUNCATE.md
mv ./reference/sql/VACUUM.html.md.erb ./reference/sql/VACUUM.md
mv ./reference/SQLCommandReference.html.md.erb ./reference/SQLCommandReference.md
mv ./reference/toolkit/hawq_toolkit.html.md.erb ./reference/toolkit/hawq_toolkit.md
mv ./requirements/system-requirements.html.md.erb ./requirements/system-requirements.md
mv ./resourcemgmt/best-practices.html.md.erb ./resourcemgmt/best-practices.md
mv ./resourcemgmt/ConfigureResourceManagement.html.md.erb ./resourcemgmt/ConfigureResourceManagement.md
mv ./resourcemgmt/HAWQResourceManagement.html.md.erb ./resourcemgmt/HAWQResourceManagement.md
mv ./resourcemgmt/index.md.erb ./resourcemgmt/index.md.erb
mv ./resourcemgmt/ResourceManagerStatus.html.md.erb ./resourcemgmt/ResourceManagerStatus.md
mv ./resourcemgmt/ResourceQueues.html.md.erb ./resourcemgmt/ResourceQueues.md
mv ./resourcemgmt/YARNIntegration.html.md.erb ./resourcemgmt/YARNIntegration.md
mv ./troubleshooting/Troubleshooting.html.md.erb ./troubleshooting/Troubleshooting.md
mv ./tutorial/gettingstarted/basicdbadmin.html.md.erb ./tutorial/gettingstarted/basicdbadmin.md
mv ./tutorial/gettingstarted/basichawqadmin.html.md.erb ./tutorial/gettingstarted/basichawqadmin.md
mv ./tutorial/gettingstarted/dataandscripts.html.md.erb ./tutorial/gettingstarted/dataandscripts.md
mv ./tutorial/gettingstarted/introhawqenv.html.md.erb ./tutorial/gettingstarted/introhawqenv.md
mv ./tutorial/gettingstarted/introhawqtbls.html.md.erb ./tutorial/gettingstarted/introhawqtbls.md
mv ./tutorial/gettingstarted/intropxfhdfs.html.md.erb ./tutorial/gettingstarted/intropxfhdfs.md
mv ./tutorial/overview.html.md.erb ./tutorial/overview.md
